import type { Metadata } from "next";
import { Geist, Geist_Mono, Cinzel, Fauna_One, Lato, Play } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const faunaOne = Fauna_One({
  weight: "400",
  variable: "--font-fauna-one",
  subsets: ["latin"],
});

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
  subsets: ["latin"],
});

const play = Play({
  weight: ["400", "700"],
  variable: "--font-play",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cinzel.variable} ${faunaOne.variable} ${lato.variable} ${play.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
